#!/usr/bin/env python3
"""
build_blocks_v2.py — Generate BUILDING_BLOCKS_v2.md from v2/entries/*.yaml.

Groups entries by claim_type (primary) then domain (secondary), and produces
a Markdown reference with a legacy F-code lookup table.

Usage:
    python scripts/build_blocks_v2.py
    Writes v2/BUILDING_BLOCKS_v2.md
"""

import io
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

# ── Ensure UTF-8 on Windows ──────────────────────────────────────────────────
if sys.platform == "win32":
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name)
        if isinstance(stream, io.TextIOWrapper):
            setattr(
                sys,
                stream_name,
                io.TextIOWrapper(stream.buffer, encoding="utf-8", errors="replace"),
            )

# ── Paths ─────────────────────────────────────────────────────────────────────
KB_ROOT = Path(__file__).resolve().parent.parent
ENTRIES_DIR = KB_ROOT / "v2" / "entries"
OUTPUT_FILE = KB_ROOT / "v2" / "BUILDING_BLOCKS_v2.md"


def load_all_entries():
    """Load every YAML entry, returning a list of dicts."""
    entries = []
    for yf in sorted(ENTRIES_DIR.glob("*.yaml")):
        try:
            with open(yf, encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if isinstance(data, dict):
                data["_source_file"] = yf.name
                entries.append(data)
        except Exception as exc:
            print(f"WARN: skipping {yf.name}: {exc}", file=sys.stderr)
    return entries


def build_markdown(entries: list[dict]) -> str:
    """Build the full Markdown string."""
    lines: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── Collect statistics ────────────────────────────────────────────────
    domains = set()
    claim_types = set()
    artifact_types = defaultdict(int)
    legacy_map: dict[str, str] = {}  # F-code -> semantic id

    for e in entries:
        domains.add(e.get("domain", "UNKNOWN"))
        claim_types.add(e.get("claim_type", "UNKNOWN"))
        artifact_types[e.get("artifact_type", "UNKNOWN")] += 1
        alias = e.get("legacy_alias", "")
        eid = e.get("id", "")
        if alias and eid:
            legacy_map[alias] = eid

    # ── Group: claim_type -> domain -> entries ────────────────────────────
    grouped: dict[str, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for e in entries:
        ct = e.get("claim_type", "UNKNOWN")
        dom = e.get("domain", "UNKNOWN")
        grouped[ct][dom].append(e)

    # ── Header ────────────────────────────────────────────────────────────
    lines.append("# BUILDING BLOCKS v2")
    lines.append("")
    lines.append(f"> Auto-generated by `build_blocks_v2.py` on {now}")
    lines.append("> Do not edit manually — regenerate with `python scripts/build_blocks_v2.py`")
    lines.append("")
    lines.append("## Statistics")
    lines.append("")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total entries | {len(entries)} |")
    lines.append(f"| Domains | {len(domains)} |")
    lines.append(f"| Claim types | {len(claim_types)} |")
    for at in sorted(artifact_types):
        lines.append(f"| Artifact: {at} | {artifact_types[at]} |")
    lines.append(f"| Legacy F-codes | {len(legacy_map)} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Main body: grouped by claim_type then domain ──────────────────────
    for ct in sorted(grouped):
        lines.append(f"## {ct}")
        lines.append("")
        domain_group = grouped[ct]
        for dom in sorted(domain_group):
            lines.append(f"### {dom}")
            lines.append("")
            for e in sorted(domain_group[dom], key=lambda x: x.get("id", "")):
                eid = e.get("id", "???")
                alias = e.get("legacy_alias", "")
                name = e.get("name_en", "Untitled")
                atype = e.get("artifact_type", "")

                legacy_part = f" (legacy: `{alias}`)" if alias else ""
                atype_part = f" [{atype}]" if atype else ""
                lines.append(f"- `{eid}`{legacy_part} — {name}{atype_part}")
            lines.append("")

    # ── Legacy Lookup ─────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("## Legacy Lookup (F-code -> Semantic ID)")
    lines.append("")
    lines.append("| F-code | Semantic ID |")
    lines.append("|--------|-------------|")

    def fcode_sort_key(fcode: str):
        """Sort F1.1 < F1.2 < F2.1 etc."""
        parts = fcode.lstrip("F").split(".")
        try:
            return tuple(int(p) for p in parts)
        except ValueError:
            return (9999,)

    for fcode in sorted(legacy_map, key=fcode_sort_key):
        lines.append(f"| `{fcode}` | `{legacy_map[fcode]}` |")
    lines.append("")

    return "\n".join(lines)


def main():
    entries = load_all_entries()
    if not entries:
        print(f"ERROR: No entries found in {ENTRIES_DIR}", file=sys.stderr)
        return 1

    md = build_markdown(entries)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"Wrote {OUTPUT_FILE} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
